create table public.games (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  grade_level integer not null,
  subject text not null,
  file_url text not null,
  thumbnail_url text,
  file_name text not null
);

alter table public.games enable row level security;

create policy "Public games are viewable by everyone"
  on public.games for select
  using ( true );

create policy "Enable insert for authenticated users only"
  on public.games for insert
  with check ( true );
