create table if not exists public.admins (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  email text not null unique,
  password text not null
);

create table if not exists public.students (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null unique,
  grade text not null,
  school_name text not null,
  password text not null
);

alter table public.admins enable row level security;
alter table public.students enable row level security;

create policy "Admins are viewable by everyone" on public.admins for select using (true);
create policy "Students are viewable by everyone" on public.students for select using (true);
